### ISSUE TITLE
Adding LiquidSoap to PiNumberStation

### ISSUE THREAD

**Issue by DonaldTsang** [korn101/PiNumberStation#11]
It would be a good idea to add LiquidSoap to PiNS:
- [x] Able to schedule when the number station plays (e.g. every night 3AM, repeated 3 times)
- [x] Able to treat number station as its own separate playlist, and use a separate script to generate the file
- [x] Able to have music from a separate playing to simulate normal radio stations

**Comment by MirkoPapella** [comment]
Hi @DonaldTsang 
You can schedule PiNs with cronjob too

**Comment by hiryu85** [comment]
Hi @DonaldTsang
You can schedule PiNs with cronjob too

**Comment by DonaldTsang** [comment]
@hiryu85 any ways of doing fade-in fade-out (playing normal playlists in regular times until a scheduled message is sent)?

**Comment by hiryu85** [comment]
Not for now... but i'am working for PiNS+liquidsoap ;-)

I assure you nothing, I work there in my spare time and it is not certain
that I will be able to conclude anything.
I'll let you know below if I'm making progress.

**Comment by DonaldTsang** [comment]
@hiryu85 well said though, since the Azuracast (Liquidsoap+Icecast suite) people really don't know how to add their software to Raspberry Pi.

**Comment by hiryu85** [comment]
https://github.com/hiryu85/PiNumberStation/tree/feature/icecast-streaming

its wip version, but works :P


ps: require icecast, and liquidsoap liquidsoap-cry

**Comment by hiryu85** [comment]
require icecast, and liquidsoap liquidsoap-cry

**Comment by DonaldTsang** [comment]
@hiryu85 update the ReadMe if necessary

**Comment by hiryu85** [comment]
* [x] Able to schedule when the number station plays (e.g. every night 3AM, repeated 3 times)
* [x] Able to treat number station as its own separate playlist, and use a separate script to generate the file
* [x] Able to have music from a separate playing to simulate normal radio stations


New commits on my fork https://github.com/hiryu85/PiNumberStation/tree/feature/icecast-streaming.

Please read doc in PiNS-icecast.py

**Comment by hiryu85** [comment]
Pull-request #12

**Comment by DonaldTsang** [comment]
@hiryu85 
1. In regards to the NATO alphabet, I would recommend creating a variation of the alphabet to differentiate upper case, lower case and special characters for base64, base58 and other encodings for use in IPFS multihash based applications.
We can get some ideas in https://en.wikipedia.org/wiki/Spelling_alphabet (if the word is 2 syllables it is upper case, if it is 3 syllables it is lower case)
2. In regards to text-to-speech libraries to deal with No.1, I would recommend https://github.com/pndurette/gTTS (since Google has the best text to speech)
3. In regards to documentation, the ReadMe does not specify where to put your music, assuming that we put it in https://github.com/hiryu85/PiNumberStation/tree/feature/icecast-streaming/streaming/default/music ?

**Comment by DonaldTsang** [comment]
A list from Wikipedia:
- A Ab Able Able/Affirm Ace Ack Actor Adam Adams Afirm Alfa Alice Alpha America Amsterdam Andrew Apple Apples Argentine Ash Authority
- B Back Baker Baltimore Bcd Beer Benjamin Bertha Beta Bills Boston Boy Bravo Brother Brussels Butter
- C Canada Canteen Capture Casablanca Cast Chain Charles Charlie Chicago Chile Coca Cork
- D Damascus Danemark David Def Delta Denmark Denver Destroy Diver Dock Dog Don Dora Dover Duff
- E Eagle Eastern Easy Echo Ecuador Eddy Eddystone Edison Edward Egg Egypt Emma England Englishmen Esses Extra
- F Father Finland Fisher Florida Fox Foxtrot Fractious France Francisco Frank Freddie Freddy Frederick
- G Gallipoli Galloping Gangway Geneva George Germany Gibraltar Gig Gold Golf Greece
- H Halliard Hanover Harry Havana Have Hawaii Henry High Honolulu Horse Hotel How Hypo
- I Ice Ida India Ink Insect Int Interrogatory Invariably Ireland Isaac Italia Italy Item
- J Jack Jake James Japan Jersey Jerusalem Jig Jockey John Johnnie Johnny Jude Jug Juggling Juliett Julietta Juliette Jérusalem
- K Kate Kentucky Khartoum Kilo Kilogramme Kilowatt Kimberley King Knapsack Knights
- L Lash Lewis Lima Lincoln Liverpool London Loose Louis Love Lucy Lugger Luxembourg
- M Madagascar Madrid Managing Mary Metro Mexico Mike Monkey Montreal Mother Mule Musket 
- N Nab/Negat Nan Nancy Nectar Negat Nellie Nelly Neptune Net Neufchatel Never New New-York Newark Nicaragua Nora Norway November Nuts
- O Oak Oble Oboe Ocean October Oliver Ontario Option Orange Oscar Oslo Ostend Otto Owners Oyster
- P Pacific Page Papa Paris Paul Peter Pip Pistol Play Polka Portugal Prep Pudding Pup
- Q Qrs Quack Quad Quadrant Quail Quaker Quebec Queen Queenie Québec
-R Radio Raft Reefer Remarks Rivoli Robert Roger Roma Romania Rome Romeo Ropert Rot Rst Rush S Sail Sam Samuel Santiago Sardinia Scout Shipmate Sierra Sugar Support Susan Sweden
- T Talk Tango Tare Texas The Thomas Tide Toc Tokio Tokyo Tom Tommy Topsail Tripoli Tuv
- U Uncle Uniform Union Unit United Unless Unload Upsala Uruguay Use Utah
- V Valencia Vast Venezuela Vessel Vic Vice Victor Victoria Victory Vindictive Vinegar Violet
- W Washington Watch Wednesday When Whiskey Whisky William Willie Winch Windage Wxy
- X X-Ray Xaintrie Xanthippe Xantippe Xerxes Xmas Xpeditiously Xray
- Y Yacht Yale Yankee Yankey Yellow Yeoman Yoke Yokohama York Yorker Young Your
- Z Zanzibar Zebra Zed Zero Zigzag Zoo Zulu Zululand Zurich

**Comment by hiryu85** [comment]
@DonaldTsang 
Thanks for suggestions

> 1. In regards to the NATO alphabet, I would recommend creating a variation of the alphabet to differentiate upper case, lower case and special characters for base64, base58 and other encodings for use in IPFS multihash based applications.
>    We can get some ideas in https://en.wikipedia.org/wiki/Spelling_alphabet (if the word is 2 syllables it is upper case, if it is 3 syllables it is lower case)

This should be another issue, because it does not concern the numbers station with LiquidSoap

> 2. In regards to text-to-speech libraries to deal with No.1, I would recommend https://github.com/pndurette/gTTS (since Google has the best text to speech)

Like above. However, I prefer the original method of linking multiple wav files into a single file. 
Becase in future i want work to another feature: "use multiple voice packs".
Allow to customize the style of the synthesizer, through a voice pack.
Each voice pack will contain the various wav files used so far and content currently in the original vo /).
This will allow the user to be able to customize according to the context to customize the synthesizer's voice.

If we used gtTTS it would not be so customizable.


> 3. In regards to documentation, the ReadMe does not specify where to put your music, assuming that we put it in https://github.com/hiryu85/PiNumberStation/tree/feature/icecast-streaming/streaming/default/music ?

Yeah, music should be put into music/ directory if want use local files. 
It is in development, which is why it is not yet documented.

**Comment by DonaldTsang** [comment]
@hiryu85 
Regarding the Uppercase Lowercase issue, I will make a new one.

About the "voice pack" issue, I was expecting that we download TTS from Google instead of streaming by demand, hope that I can make it clear. I understand that there are other TTS as well, and that compatibility should be allowed, but Google's TTS sounded the most "real" (which is why it is my persoanl preference).

Regarding the music part, it is understandable that it is not fully developed yet.

**Comment by hiryu85** [comment]
@DonaldTsang 

> About the "voice pack" issue, I was expecting that we download TTS from Google instead of streaming by demand, hope that I can make it clear. I understand that there are other TTS as well, and that compatibility should be allowed, but Google's TTS sounded the most "real" (which is why it is my persoanl preference).

Regarding the fact that it is clearer I agree, but with this method honestly you lose a lot of configuration, and that's why I still prefer that "PiNS" creates audio based on * .wav files because as I said in the previous answer is a method that is more flexible because in the future through _voice-packs_ it will allow to set a different voice of the syntethizer based on the radio/streaming transmission.

Using TTs in addition to using two types of voice (if possible) you lose this possibility.
However, you can always override the constructWav function and let it use gTTs ;-).
Open another issue about it, thanks.

**Comment by DonaldTsang** [comment]
@hiryu85 I was talking about downloading pre-TTSed wav files from Google, Amazon and such. The *.wav format is pretty useful after all.

**Comment by hiryu85** [comment]
> @hiryu85 I was talking about downloading pre-TTSed wav files from Google, Amazon and such. The *.wav format is pretty useful after all.

I'm sorry I didn't understand, it can be useful.
As soon as I finish this feature, I work on that of voice-packs and integrate a script to generate them using google translate.

Thanks for the suggestion

**Comment by DonaldTsang** [comment]
@hiryu85 made https://github.com/korn101/PiNumberStation/issues/13 for the other issue
