### ISSUE TITLE
Add "repeat_times" and "repeat_interval_break_seconds" to control message repeats

### ISSUE THREAD

**Issue by aspadistra** [korn101/PiNumberStation#2]
Add "repeat_times" and "repeat_interval_break_seconds" to control message repeats ...

**Comment by korn101** [comment]
You're welcome to make the changes and issue a merge request :)

**Comment by hiryu85** [comment]
See pull request #8

**Comment by korn101** [comment]
Merged the pull request by @hiryu85.
