### ISSUE TITLE
Raspberry 2 and 3

### ISSUE THREAD

**Issue by tdwgm** [korn101/PiNumberStation#3]
Please make raspberry 2 and 3 compatible with PiNumberStation.

**Comment by korn101** [comment]
I wish I could, but I don't currently own one @Monkeyfacemoney. You could try get it working with https://github.com/asmello/fm_transmitter, then place a merge request and I will accept it.

**Comment by hiryu85** [comment]
Hello,
With fm_transmitter instead PiFm works fine on my Raspberry Pi2﻿.
I will send a pull request ;-)

**Comment by hiryu85** [comment]
Hi @Monkeyfacemoney, try my pull request n #6

**Comment by korn101** [comment]
Merged the fix for this issue as supplied by @hiryu85. Thanks again hiryu.
